server:
  port: 9001
  tomcat:
    # TCP ??? ???? ??? HTTP ??? ???? ??? ??? ???? ??
    connection-timeout: 2s
    # ??? http ??? ???? ?? ??? ???? ??
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
