apiVersion: v1 # 서비스 객체의 API 버전
kind: Service # 생성할 객체의 유형
metadata:
  name: catalog-service # 서비스 이름. 유효한 DNS 이름이어야 한다.
  labels:
    app: catalog-service # 서비스에 추가할 레이블
spec:
  type: ClusterIP # 서비스의 유형
  selector:
    app: catalog-service # 대상으로 삼고 노출해야 하는 파드를 찾는 데 사용할 레이블
  ports:
    - protocol: TCP # 서비스가 사용할 네트워크 프로토콜
      port: 80 # 서비스가 노출할 포트
      targetPort: 9001 # 서비스의 대상이 되는 파드가 노출할 포트